services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: users
    environment:
      POSTGRES_PASSWORD: 55555
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: